name: Lint and Format Python files

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  python-lint-format:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - tool: "black"
            args: "--check"
          - tool: "flake8"
            args: "--ignore=E501"
          - tool: "isort"
            args: "--check --diff"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.3.5

      - name: Install Python 3.9
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9

      - name: Install ${{ matrix.tool }}
        run: |
          python -m pip install --upgrade pip
          python -m pip install ${{ matrix.tool }}

      - name: Run ${{ matrix.tool }}
        run: |
          ${{ matrix.tool }} ${{ matrix.args }} .
